[package]
name = "libcharm"
version = "0.1.0"
edition = "2024"

[features]
js = ["uuid/js"]

[dependencies]
ed25519-dalek = "2.1.1"
serde = { version = "1.0.219", features = ["derive"] }
base64 = "0.22.1"
uuid = { version = "1.16.0", features = ["v4"] }
